name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    name: Install package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install package
        run: |
        sudo apt update
        sudo apt install -y python3-pip
        python3 -m pip install --upgrade pip numpy scipy pytest
        python3 -m pip install -e .[test]

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: install

    steps:
      - name: Run tests
        run: python3 -m pytest
